
export const SET_NOVEL_RIGHTSHOW = 'SET_NOVEL_RIGHTSHOW';
export const SET_NOVEL_BACKCOLOR = 'SET_NOVEL_BACKCOLOR';
export const UPDATE_CLIENTARTICLEINFO = 'UPDATE_CLIENTARTICLEINFO';
export const UPDATE_CLIENTVALUE = 'UPDATE_CLIENTVALUE';

export const GET_ARTICLE_COMMENT = 'GET_ARTICLE_COMMENT';
