export const UPDATE_VALUE = 'UPDATE_VALUE';

export const GET_HOMEPAGE_ARTICLE = 'GET_HOMEPAGE_ARTICLE';
export const GET_ARTICLE_DETAILS = 'GET_ARTICLE_DETAILS';
export const GET_ARTICLE_BYTYPE = 'GET_ARTICLE_BYTYPE';
export const GET_ARTICLE_RECOMMEND = 'GET_ARTICLE_RECOMMEND';
export const GET_ARTICLE_BYTYPE_LIST = 'GET_ARTICLE_BYTYPE_LIST';
export const RESET_ARTICLE = 'RESET_ARTICLE';

export const SET_NOVEL_RIGHTSHOW = 'SET_NOVEL_RIGHTSHOW';
export const SET_NOVEL_BACKCOLOR = 'SET_NOVEL_BACKCOLOR';
export const UPDATE_CLIENTARTICLEINFO = 'UPDATE_CLIENTARTICLEINFO';
export const UPDATE_CLIENTVALUE = 'UPDATE_CLIENTVALUE';

export const GET_ARTICLE_COMMENT = 'GET_ARTICLE_COMMENT';


export const MUSIC_SEARCH = 'MUSIC_SEARCH';
